import Product from '~/assets/new_product.png'
import Product2 from '~/assets/product2.png'
import Product3 from '~/assets/product-3.png'

export const BEST = [
    {
        id:1,
        img: Product,
        sub: 'NEW',
        name: 'Skullcandy - Crusher anc 2 wireless headphones',
        price: '$299.99',
    },
    {   id:2,
        img: Product2,
        sub: 'NEW',
        name: 'Skullcandy - Crusher anc 2 wireless headphones',
        price: '$299.99',
    },
    {   id:3,
        img: Product3   ,
        sub: 'NEW',
        name: 'Skullcandy - Crusher anc 2 wireless headphones',
        price: '$299.99',
    },
    {   id:4,
        img: Product,
        sub: 'NEW',
        name: 'Skullcandy - Crusher anc 2 wireless headphones',
        price: '$299.99',
    },
    {   id:5,
        img: Product,
        sub: 'NEW',
        name: 'Skullcandy - Crusher anc 2 wireless headphones',
        price: '$299.99',
    },
    {   id:6,
        img: Product,
        sub: 'NEW',
        name: 'Skullcandy - Crusher anc 2 wireless headphones',
        price: '$299.99',
    },    
    {   id:7,
        img: Product,
        sub: 'NEW',
        name: 'Skullcandy - Crusher anc 2 wireless headphones',
        price: '$299.99',
    },
    {   id:8,
        img: Product,
        sub: 'NEW',
        name: 'Skullcandy - Crusher anc 2 wireless headphones',
        price: '$299.99',
    },   
           
]